#!/usr/bin/env python3
"""
Reads button icon PNGs, base64-encodes them as thumbnails, and generates
a C header with the icon manifest as a PROGMEM JSON string.

Usage: python3 scripts/generate_icon_manifest.py
Output: src/generated/icon_manifest.h
"""

import base64
import json
import os
import glob
from PIL import Image
from io import BytesIO

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
ICONS_DIR = os.path.join(PROJECT_ROOT, 'icons-buttons')
OUTPUT = os.path.join(PROJECT_ROOT, 'src', 'generated', 'icon_manifest.h')
THUMB_SIZE = 32  # Thumbnail size for web UI


def escape_for_c(s: str) -> str:
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s


def main():
    entries = []

    for path in sorted(glob.glob(os.path.join(ICONS_DIR, '*.png'))):
        filename = os.path.basename(path)
        if filename.endswith('-off.png'):
            continue  # Skip off variants - picker shows on icons, derives off name
        icon_id = filename.replace('.png', '').replace('-', '_')
        title = filename.replace('.png', '').replace('-', ' ').title()

        # Create thumbnail
        img = Image.open(path).convert('RGBA')
        white_bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
        img = Image.alpha_composite(white_bg, img)
        img = img.resize((THUMB_SIZE, THUMB_SIZE), Image.Resampling.LANCZOS)
        img = img.convert('RGB')

        buf = BytesIO()
        img.save(buf, format='PNG', optimize=True)
        b64 = base64.b64encode(buf.getvalue()).decode('ascii')
        data_uri = f"data:image/png;base64,{b64}"

        entries.append({
            'id': icon_id,
            'title': title,
            'data': data_uri,
        })

        print(f"  {icon_id}: {len(buf.getvalue())} bytes")

    if not entries:
        print("Error: no icons found", file=__import__('sys').stderr)
        return

    payload = json.dumps(entries, separators=(',', ':'))
    escaped = escape_for_c(payload)

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

    lines = [
        '#pragma once',
        '',
        '// Auto-generated by scripts/generate_icon_manifest.py',
        '',
        '#include <pgmspace.h>',
        '',
        'static const char ICON_MANIFEST_JSON[] PROGMEM =',
        f'    "{escaped}\\n";',
        '',
    ]

    with open(OUTPUT, 'w') as f:
        f.write('\n'.join(lines))

    print(f"\nGenerated {OUTPUT}")
    print(f"  {len(entries)} icons, {os.path.getsize(OUTPUT):,} bytes")


if __name__ == '__main__':
    main()
